# Generated by Django 4.0.2 on 2022-02-24 14:06

import VMS.validations
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0009_orders_status_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('destination_1', models.CharField(max_length=15)),
                ('destination_2', models.CharField(max_length=15)),
                ('destination_3', models.CharField(max_length=15)),
                ('destination_4', models.CharField(max_length=15)),
                ('destination_5', models.CharField(max_length=15)),
                ('destination_6', models.CharField(max_length=15)),
                ('destination_7', models.CharField(max_length=15)),
                ('destination_8', models.CharField(max_length=15)),
                ('destination_9', models.CharField(max_length=15)),
                ('destination_10', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='VMS.base')),
                ('first_name', models.CharField(max_length=15, validators=[VMS.validations.name])),
                ('last_name', models.CharField(max_length=15, validators=[VMS.validations.name])),
                ('phone1', models.IntegerField(default=0, validators=[VMS.validations.phoneNumber])),
                ('phone2', models.IntegerField(default=0, validators=[VMS.validations.phoneNumber])),
                ('email', models.EmailField(default='', max_length=150)),
                ('branch', models.CharField(default='', max_length=15, validators=[VMS.validations.name])),
                ('base_location', models.CharField(default='', max_length=15, validators=[VMS.validations.name])),
                ('zip_code', models.IntegerField(default=0, validators=[VMS.validations.zipCode])),
                ('address', models.CharField(max_length=200)),
                ('driving_time', models.CharField(choices=[('Day', 'DAY'), ('Night', 'NIGHT'), ('Day + Night', 'DAY + Night')], default='day', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'ACTIVE'), ('Engage', 'ENGAGE'), ('InActive', 'INACTIVE')], default='Active', max_length=10)),
                ('experience', models.CharField(choices=[('1', 'Less then 1 year'), ('2 - 4', 'Between 2 - 4 Years'), ('4 - 6', 'Between 4 - 6 Years'), ('6+', 'More than 6+ Years')], default='2 - 4', max_length=20)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('salary', models.IntegerField(default=0)),
            ],
            bases=('VMS.base',),
        ),
        migrations.CreateModel(
            name='DriverDoc',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='VMS.base')),
                ('license_img', models.ImageField(default='', upload_to='driversDocs/images')),
                ('license_no', models.CharField(max_length=15, validators=[VMS.validations.license])),
                ('license_exp_date', models.DateField()),
                ('adharCard_img', models.ImageField(default='', upload_to='driversDocs/images')),
                ('adharCard_no', models.CharField(max_length=15, validators=[VMS.validations.adharCard])),
                ('panCard_img', models.ImageField(default='', upload_to='driversDocs/images')),
                ('panCard_no', models.CharField(max_length=15, validators=[VMS.validations.panCard])),
                ('marritial_status', models.CharField(max_length=20)),
                ('driver_image', models.ImageField(default='', upload_to='drivers/images')),
            ],
            bases=('VMS.base',),
        ),
        migrations.CreateModel(
            name='DriverNote',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='VMS.base')),
                ('message', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
            ],
            bases=('VMS.base',),
        ),
        migrations.CreateModel(
            name='VehicleDoc',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='VMS.base')),
                ('owner_name', models.CharField(default='', max_length=15, validators=[VMS.validations.ownerName])),
                ('owner_phone', models.IntegerField(default=0, validators=[VMS.validations.phoneNumber])),
                ('rc_book', models.ImageField(default='', upload_to='vehiclesDocs/images')),
                ('rc_number', models.CharField(default='', max_length=15, validators=[VMS.validations.rcNumber])),
                ('papers_img', models.ImageField(default='', upload_to='vehiclesDocs/images')),
                ('permit', models.ImageField(default='', upload_to='vehiclesDocs/images')),
            ],
            bases=('VMS.base',),
        ),
        migrations.CreateModel(
            name='VehicleMaintainance',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='VMS.base')),
                ('last_service', models.DateField()),
                ('insurance_policy_no', models.CharField(default='', max_length=12, validators=[VMS.validations.policyNumber])),
                ('insurance_exp', models.DateField()),
                ('puc_no', models.CharField(default='', max_length=12, validators=[VMS.validations.pucNumber])),
                ('puc_exp', models.DateField()),
            ],
            bases=('VMS.base',),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='VMS.base')),
                ('model', models.CharField(max_length=30)),
                ('ownerShip', models.CharField(choices=[('Company', 'COMPANY'), ('Joint Tenants', 'JOINT TENANTS'), ('Business Partners', 'BUISNESS PARTNERS')], default='Company', max_length=30)),
                ('vehicle_type', models.CharField(choices=[('Truck', 'TRUCK'), ('Mini Truck', 'MNI TRUCK'), ('Heavy Truck', 'HEAVY TRUCK'), ('Tempo', 'TEMPO'), ('Cargo', 'CARGO')], max_length=15)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'PETROL'), ('Diesel', 'DIESEL'), ('CNG', 'CNG'), ('Electric', 'ELECTRIC')], default='Diesel', max_length=15)),
                ('permit_type', models.CharField(choices=[('City', 'CITY'), ('State', 'STATE'), ('National', 'NATIONAL')], default='State', max_length=15)),
                ('branch', models.CharField(default='', max_length=15)),
                ('current_branch', models.CharField(default='', max_length=12)),
                ('status', models.CharField(choices=[('Active', 'ACTIVE'), ('Engage', 'ENGAGE'), ('InActive', 'INACTIVE')], default='Active', max_length=15)),
                ('carrying_capacity', models.CharField(default='', max_length=15)),
                ('carrying_space', models.CharField(default='', max_length=15)),
                ('length', models.FloatField(default=0)),
                ('breadth', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('number_plate', models.CharField(default='', max_length=30, validators=[VMS.validations.vehicleNumber])),
                ('vehicle_image', models.ImageField(default='', upload_to='vehicles/images')),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.vehicledoc')),
                ('maintainence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.vehiclemaintainance')),
            ],
            bases=('VMS.base',),
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=15)),
                ('departure_time', models.CharField(max_length=15)),
                ('departure_loc', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=15)),
                ('estimated_time', models.CharField(max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'ACTIVE'), ('Delivered', 'DELIVERED'), ('Cancelled', 'CANCELLED')], default='Ready to deliver', max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orders')),
                ('routes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.routes')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='documents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.driverdoc'),
        ),
        migrations.AddField(
            model_name='driver',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VMS.drivernote'),
        ),
    ]
