# Generated by Django 4.0.2 on 2022-02-24 19:49

import VMS.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdoc',
            name='full_name',
            field=models.CharField(default='', max_length=50, validators=[VMS.validations.fullName]),
        ),
    ]
