# Generated by Django 4.0.2 on 2022-02-24 20:18

import VMS.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0002_driverdoc_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='base_location',
            field=models.CharField(default='', max_length=15, validators=[VMS.validations.fullName]),
        ),
        migrations.AlterField(
            model_name='driver',
            name='branch',
            field=models.CharField(default='', max_length=15, validators=[VMS.validations.fullName]),
        ),
        migrations.AlterField(
            model_name='vehicledoc',
            name='owner_name',
            field=models.CharField(default='', max_length=25, validators=[VMS.validations.fullName]),
        ),
    ]
