# Generated by Django 4.0.2 on 2022-02-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0004_rename_documents_vehicle_owner_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='owner_name',
            new_name='owners_name',
        ),
    ]
