# Generated by Django 4.0.2 on 2022-02-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0005_rename_owner_name_vehicle_owners_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='owners_name',
            new_name='Rc_number',
        ),
    ]
