# Generated by Django 4.0.2 on 2022-02-24 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0006_rename_owners_name_vehicle_rc_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='documents',
            new_name='license_no',
        ),
        migrations.RemoveField(
            model_name='driverdoc',
            name='full_name',
        ),
    ]
