# Generated by Django 4.0.2 on 2022-02-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0007_rename_documents_driver_license_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdoc',
            name='marritial_status',
            field=models.CharField(choices=[('Single', 'SINGLE'), ('Married', 'MARRIED')], default='Single', max_length=20),
        ),
    ]
