# Generated by Django 4.0.2 on 2022-02-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VMS', '0009_remove_travel_departure_loc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travel',
            old_name='order',
            new_name='order_id',
        ),
    ]
