# Generated by Django 4.0.2 on 2022-02-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210409_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('InActive', 'INACTIVE')], default='Active', max_length=15),
        ),
    ]
