# Generated by Django 4.0.2 on 2022-02-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogpost_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='head0',
            new_name='head',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='chead0',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='chead1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='chead2',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head1',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='head2',
        ),
    ]
