# Generated by Django 4.0.2 on 2022-02-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orders_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('InActive', 'INACTIVE')], default='Active', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('InActive', 'INACTIVE')], default='Active', max_length=15),
        ),
    ]
