# Generated by Django 4.0.2 on 2022-02-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orders_status_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proContent',
            field=models.CharField(default='', max_length=300),
        ),
    ]
