# Generated by Django 4.0.2 on 2022-02-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_procontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='proContent',
            field=models.TextField(default=''),
        ),
    ]
