# Generated by Django 4.0.2 on 2022-02-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_procontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
