# Generated by Django 4.0.2 on 2023-02-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_orders_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('InActive', 'INACTIVE'), ('Cancelled', 'CANCELLED')], default='Active', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('InActive', 'INACTIVE'), ('Cancelled', 'CANCELLED')], default='Active', max_length=15),
        ),
    ]
